clear; clc;
% Load the phase space scan data. The data set was generated by Siarhei Hladyshau 
T = readmatrix("../FigureData/Figure4A.xlsx");
% Scaling factor to convert concentrations from zeptomoles to molecules
SF = 10^(-21)*6.02*10^(23);
% Scale k1 and k2 to be consistent 
k1 = T(1,2:end)/SF/SF; k2 = T(2:end,1);
regime_score = T(2:end,2:end);

figure
hold on;
axis xy;
imagesc(regime_score);

colormap(hot);
xlim([0,Inf])
ylim([0,Inf])

xlabel('k_1');
xticks([0:50:200])
xticklabels([k1(1):0.5/SF/SF:k1(end)])

yticks([0:50:200])
yticklabels([k2(1):0.5:k2(end)])
axis square
ylabel('k_2');
box on;
set(gca, 'FontSize', 18, 'LineWidth', 5);